eval_setting:
  split:
    RS: [ 0.8, 0.1, 0.1 ]
  order: RO
  group_by: user
  mode: full

epochs: 300

learner: Adam
learning_rate: 0.002

seed: 2022

eval_batch_size: 4096000
valid_metric: Recall@10
metrics: [ "Recall", "Hit"]
topk: [ 10, 20, 50]
